### ISSUE TITLE
A bunch of errors

### ISSUE THREAD

**Issue by ghost** [ThePotato97/PhasmophobiaPotatoGUIPublic#11]
First upload builds perfectly. Now after the commits it wouldn't build.
![image](https://user-images.githubusercontent.com/47246451/97995266-f5e85c80-1dee-11eb-87e0-ebe7f6cef805.png)

**Comment by ThePotato97** [comment]
You're missing the assemblies

**Comment by Gavur** [comment]
Use RUNME.bat and THEN open the solution and check references before compiling.

**Comment by ghost** [comment]
Idk what I'm missing. The folder created by RUNME.bat is linked with the melonloader folder correctly. Why do I get all the errors about missing files?

**Comment by Gavur** [comment]
Click on your "references" menu in your solution explorer tab and check them.

**Comment by ThePotato97** [comment]
> 
> 
> Idk what I'm missing. The folder created by RUNME.bat is linked with the melonloader folder correctly. Why do I get all the errors about missing files?

are the assemblies in the melonloader managed folder?

**Comment by Gavur** [comment]
Yep they are

**Comment by Gavur** [comment]
So basically every "using" statement in class files must be added to references aswell otherwise "using" statements would not work.

**Comment by ThePotato97** [comment]
> 
> 
> Yep they are

how do you know they are?

**Comment by Gavur** [comment]
Coz it literally says that in error log ^^

**Comment by Gavur** [comment]
And in VS19 even if you used that .bat linking method in a new project it sometimes wants you to click on a reference in solution explorer to work ^^ its a common glitch I've oftenly seen for like a year. So untill the user tries to add references manually they think there's a bug in the project. But when they do they'll see that they're gone... Like Schrödinger's cat, right?

**Comment by cristyanul** [comment]
I never had something like that happen to anything I made in C#.
I can't figure out what to do..

> Click on your "references" menu in your solution explorer tab and check them.

Check what?

**Comment by ThePotato97** [comment]
> 
> 
> I never had something like that happen to anything I made in C#.
> I can't figure out what to do..
> 
> > Click on your "references" menu in your solution explorer tab and check them.
> 
> Check what?
> ![image](https://user-images.githubusercontent.com/47246451/98045789-b3943f00-1e31-11eb-8f49-8446ee445f65.png)

are the assemblies in the melonloader managed folder?

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/47246451/98046734-66b16800-1e33-11eb-8963-39b03d66b953.png)
I think everything is there.

**Comment by ThePotato97** [comment]
you have nothing from the game there

**Comment by ghost** [comment]
> you have nothing from the game there

I installed the melonloader how it should be installed. What's the problem?

**Comment by Gavur** [comment]
> you have nothing from the game there

true



> > I never had something like that happen to anything I made in C#.
> > I can't figure out what to do..
> > > Click on your "references" menu in your solution explorer tab and check them.
> > 
> > 
> > Check what?
> > ![image](https://user-images.githubusercontent.com/47246451/98045789-b3943f00-1e31-11eb-8f49-8446ee445f65.png)
> 
> are the assemblies in the melonloader managed folder?

and there're lots of warnings on them as you can see which will result in missing assembly reference errors like this pal's case

**Comment by Gavur** [comment]
![example](https://user-images.githubusercontent.com/20716541/98047250-acbef980-1e3c-11eb-89cc-ff41d69b429b.png)
it should look like this



> > you have nothing from the game there
> 
> I installed the melonloader how it should be installed. What's the problem?

Click on "Project/Add reference" and add each DLLs you'll see on classes such as "Using UnrealEngine" is pointing to UnityEngine.dll, UnityEngine.Core.dll etc.

**Comment by ThePotato97** [comment]
you didn't run the game so it didn't dump the DLLs and if you're getting an error like
![image](https://user-images.githubusercontent.com/10260415/98047567-0961ea80-1e24-11eb-93df-24d4a0781c90.png)
you need to install https://github.com/ThePotato97/PotatoLoader/releases/download/v0.2.7.2/MelonLoader.Installer.exe

**Comment by Gavur** [comment]
> you didn't run the game so it didn't dump the DLLs and if you're getting an error like
> ![image](https://user-images.githubusercontent.com/10260415/98047567-0961ea80-1e24-11eb-93df-24d4a0781c90.png)
> you need to install https://github.com/ThePotato97/PotatoLoader/releases/download/v0.2.7.2/MelonLoader.Installer.exe

I doubt that. ML is also has a bug that occured to all my friends who are in grasps of idiocy, ehm let me clarify: if you create Mods folder yourself before running the game (can't reproduce that, odd) or interrupting first launch actions even if you launch later you can go in game but ML can't extract DLLs and can't inject them either but it will run however.

**Comment by ghost** [comment]
I reinstalled MelonLoader, ran the game, built PotatoGUI and it works. Thank you both for the help!
