### ISSUE TITLE
This GUI will no longer work due to MelonLoader no longer supporting Phasmophobia.

### ISSUE THREAD

**Issue by zorinn** [ThePotato97/PhasmophobiaPotatoGUIPublic#19]
[https://cdn.discordapp.com/attachments/733305093264375849/774005743224881182/unknown.png](url)

I thought you guys would like to know that this will no longer work. Thank you and have a good day!

And if you already know, I apologize for inconveniencing you.

**Comment by ThePotato97** [comment]
#16
