### ISSUE TITLE
Namespace errors

### ISSUE THREAD

**Issue by KebabBurken** [ThePotato97/PhasmophobiaPotatoGUIPublic#2]
So i tried changing the net framework, but i think in the reference somewhere i saw it was for Net Framework 4.7.2, Im pretty trash at Visual Studios and Coding in general, i have no idea how to fix "The type or name space name 'MelonLoader' could not be found (are you missing a using directive or an assembly reference?)" in Main.cs

Would you or anyone please like to guide me into how to resolve this issue? 
Thanks in advance!

[Screenshot](https://i.imgur.com/WROyZTc.png)

**Comment by ThePotato97** [comment]
did you run the batch file?

**Comment by KebabBurken** [comment]
yes

**Comment by KebabBurken** [comment]
> did you run the batch file?

yes, [Screenshot of the batch file](https://i.imgur.com/RSOFLmN.png)

The batch file only works once, if i want to rinse and repeat, how do i do it? or how do i do the same thing the batch file does, but manually?

**Comment by KebabBurken** [comment]
Ok so i tested out the new files, the batch file finally did its thing, i opened the .sln file and built it, but im still getting namespace errors, 52 Errors, before i used to have for example "Melonloader" namespace error, only that one is fixed, im still getting "Photon, InputSystem, etc.

I cant seem to figure out how to resolve the namespace errors, (Yes i have ran the batch file as admin)

**Comment by ThePotato97** [comment]
did you run the game so it dumped the files?

**Comment by KebabBurken** [comment]
> did you run the game so it dumped the files?

Yes i have had the game run several times haha

**Comment by ThePotato97** [comment]
figured it out?

**Comment by KebabBurken** [comment]
i have no clue haha, but it worked somehow this time

**Comment by ThePotato97** [comment]
Nice be sure to sync up with the repo i added item spawning some stuff on the list doesn't work though

**Comment by KebabBurken** [comment]
I did sync up then i tried it again, im testing it out in game rn, does this version prevent from crashing?

**Comment by ThePotato97** [comment]
> 
> 
> I did sync up then i tried it again, im testing it out in game rn, does this version prevent from crashing?

It should, if you get gc thread error open another issue.

**Comment by KebabBurken** [comment]
Alright cool, also could u add an option to move mouse when menu is open, without being able to interact with the game?
