### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by hyxki** [ThePotato97/PhasmophobiaPotatoGUIPublic#3]
**Fatal error in GC**

Collecting from unknown thread
<img width="1920" alt="dsafdsfsdfdsf" src="https://user-images.githubusercontent.com/73779757/97802475-7bee8280-1bf8-11eb-8fa0-d6b7f7e377f0.PNG">

No errors inside of Melon Loader

**Comment by hyxki** [comment]
now whenever i try to build i get millions of errors

**Comment by KebabBurken** [comment]
Well from the first picture i am just gonna assume you are using the outdated dll, add me on discord, ill send you the dll i managed to build, we can see if you crash from that one.

Ecstasy#8008 (When you add me let me know who you are after i accepted)

**Comment by hyxki** [comment]
added 

- hyxki#0666

**Comment by DetermineAbsurd** [comment]
Was getting the same crash intermittently last night. I'm going to pull the latest commits and rebuild everything to see if I have the same problem.

**Comment by DetermineAbsurd** [comment]
After doing various testing with the latest builds I am unable to reproduce the error again.

**Comment by Pohy101** [comment]
I just got an error, collecting dll 30 minutes ago from the latest files.

**Comment by ghost** [comment]
I was able to reproduce this error with the latest commits. I was playing with 2 friends for about 10 minutes. Crash.
And after restarting the game and playing with the same team for about 15 minutes I had the same thing happen.

**Comment by DetermineAbsurd** [comment]
Yeah just had the same thing happen again after playing with friends. I wasn't able to reproduce it playing alone.

**Comment by Gavur** [comment]
Can you try it again now? IEnumerate had an effect on it for me.

**Comment by DetermineAbsurd** [comment]
Before this most recent breaking update, I believe that the crashing was fixed. I was using a build from 6f801d482f4c9334d9b9fc359627ec8b8735318c.
